### PR TITLE
Create Dockerfile linter workflow

### PR DESCRIPTION
**Pull request by szepeviktor**
I see the develop branch is not in use.

### CODE REVIEW

**Comment by szepeviktor** [comment]
❔
Would you like to pin image and package versions or _flow_ with latest versions?

**Comment by szepeviktor** [comment]
@janosmiko Please help. This bot is alive!

**Comment by janosmiko** [comment]
Yep, the develop branch is not officially supported. It is used to test image builds as it pushes the images to a separate docker account to make sure we are not overwriting the production ones.

**Comment by janosmiko** [comment]
Also, there are some images that can go with the latest tags. Most of them are already pinned. At some point (in a few weeks) I'll check and update the hadolint settings and update them if necessary but now I'm full with internal tasks

**Comment by janosmiko** [comment]
Closed in flavor of #50

**Pull request closed without merging**
